# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

EAPI="2"

MODULE_AUTHOR="FLORA"

inherit perl-module

DESCRIPTION="Emulate Class::Accessor::Fast behavior using Moose attributes"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~x86"
IUSE=""

DEPEND="dev-perl/namespace-clean
	dev-perl/Test-Exception
	dev-perl/Moose
	dev-lang/perl"
