# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

EAPI="2"

MODULE_AUTHOR="STEVAN"

inherit perl-module

DESCRIPTION="A Visitor for finding an element in a Tree::Simple hierarchy with a path"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~x86"
IUSE=""

DEPEND="dev-perl/Test-Exception
	dev-perl/Tree-Simple
	dev-lang/perl"
