# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

EAPI="2"

MODULE_AUTHOR="FLORA"

inherit perl-module

DESCRIPTION="Setup a CGI enviroment from a HTTP::Request"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~x86"
IUSE=""

DEPEND="dev-perl/URI
	>=dev-perl/libwww-perl-5.836
	dev-perl/Class-Accessor
	dev-lang/perl"
